name: demo CICD with Rasa X

on: [push, pull_request]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Train and Test the bot
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: "2.8.2-full"
          github_token: ${{ secrets.GITHUB_TOKEN }}
